### ISSUE TITLE
site doesn't work on safari?

### ISSUE THREAD

**Issue by vykster** [cal-itp/website#16]

**Comment by allejo** [comment]
Do you have any more details on this? It's loading fine for me on Safari

![image](https://user-images.githubusercontent.com/1246453/116457296-12060d00-a818-11eb-89e9-fe2772c68903.png)

**Comment by vykster** [comment]
@harrisonpeck was it you that mentioned this issue?

**Comment by harrisonpeck** [comment]
nope, my comment was about mobimart on iphones.

**Comment by vykster** [comment]
Yes, this one was something said to me a month ago. @allejo let's just close this out for now and next time something similar happens i'll get it documented for reproduction.
