### ISSUE TITLE
3 content updates

### ISSUE THREAD

**Issue by esquared415** [cal-itp/website#19]
Hello! Our calitp.org site needs **3 content updates** to reflect current project status + correct a newly outdated email address. Below please find the 3 site sections that need a text update + the _existing_ text & **new** text and hyperlinks. 

Please reach out to me + Harrison (& CC Jess) with any Qs. Thanks!

**1. _Section:_ Enabling contactless payments**
_Graph 2, current text:_
Starting with Monterey-Salinas Transit, Cal-ITP and partners like Visa will soon demonstrate how a transit provider that has traditionally used cash and agency-specific fare cards can accept contactless bank card payments like any other merchant.

_Graph 2, **new** text:_
Starting with [Monterey-Salinas Transit](https://mst.org/news_items/monterey-salinas-transit-announces-launch-of-contactless-fare-payment-demonstration/), Cal-ITP and partners like Visa are demonstrating how a transit provider that has traditionally used cash and agency-specific fare cards can accept contactless bank card payments like any other merchant.

**2. _Section:_ Connect with Cal-ITP**
_Current text:_
Drop us a line at calitp@dot.ca.gov to

_**New** text:_
Drop us a line at [hello@calitp.org](hello@calitp.org) to

**3. _Section:_ Stay up to date**
_Current text:_
See our [latest milestones](https://dot.ca.gov/cal-itp), and check back for more project updates—like a website to help transit providers adopt contactless payment systems.

_**New** text:_
See our [latest milestones](https://dot.ca.gov/cal-itp), and subscribe to the [Caltrans Mobility Newsletter](https://lp.constantcontactpages.com/su/eLbtFoE/calitp?website), a free biweekly resource with frequent Cal-ITP project updates.

**Comment by esquared415** [comment]
@thekaveman @allejo Hello! Wondering if there's a timeline for when this ticket's requested site edits might be implemented? Thanks!

**Comment by allejo** [comment]
Sorry about that! I have this on my todo list for tonight 😄 I'll have a PR for you to review tomorrow
