### ISSUE TITLE
select and add license

### ISSUE THREAD

**Issue by vykster** [cal-itp/website#2]

**Comment by krainboltgreene** [comment]
Selected https://firstdonoharm.dev/

**Comment by vykster** [comment]
Kurtis this needs to go through some review. Reopening and assigning to myself.

**Comment by krainboltgreene** [comment]
👍

**Comment by thekaveman** [comment]
Per Cal-ITP standard practice, repo should be licensed under either AGPLv3 or Apache 2.0.

**Comment by krainboltgreene** [comment]
I'll relicense under AGPLv3.
