### ISSUE TITLE
Homepage: New text blocks + PDF to upload and link to

### ISSUE THREAD

**Issue by esquared415** [cal-itp/website#27]
Hello! To reflect the launch of Cal-ITP Benefits and the release of the Market Sounding on Mobility Accounts, GG asked that we make edits to the calitp.org homepage:

**1. Automating customer discounts**
_Change text block under this header **from**:_
Cal-ITP is working with state partners to streamline the process for riders to instantly qualify for and receive discounts across all California transit providers without having to prove eligibility to each agency. Older adults, youth, lower-income riders, veterans, people with disabilities, and others will be able to access free or reduced fares without the hassle of paperwork.

_**to**:_
Our [Cal-ITP Benefits](https://benefits.calitp.org/) web application streamlines the process for transit riders to instantly qualify for and receive discounts, starting with [Monterey-Salinas Transit](https://mst.org/about-mst/news/) (MST), which offers a half-price Senior Fare. Now older adults (65+) with a California DMV–issued ID are able to access MST's reduced fares without the hassle of paperwork. 

We worked with state partners on this product launch, and next we're working to bring youth, lower-income riders, veterans, people with disabilities, and others the same instant access to free or reduced fares across all California transit providers, without having to prove eligibility to each agency. 

**2. Getting to work**
_Change **2nd text block** (**do not amend paragraph 1**) under this header **from**:_
In August 2020, Cal-ITP and partners gathered input from marketplace companies to gauge capabilities and interest in supporting payment issuance. Cal-ITP’s 3rd Market Sounding Report: Payment Issuance for California Transit was published in December 2020.

_**to** (and please notice Design's varying "colored highlight" text treatment for links in this section):_
In 2020, Cal-ITP and partners gathered input from marketplace companies to gauge capabilities and interest in supporting payment issuance. The findings were documented in Cal-ITP’s [3rd Market Sounding Report: Payment Issuance for California Transit](https://dot.ca.gov/-/media/dot-media/cal-itp/documents/cal-itp-payment-issuance-market-sounding-response-summary-report-final-a11y.pdf) and led to Cal-ITP collaborating with the California Air Resources Board (CARB) in 2021 to understand the market for mobility accounts. Highlights from interviews with companies, transit agencies, and nonprofit and academic stakeholders can be found in the [Market Sounding Report: Mobility Accounts](url).

**_For this new url, please link to an upload of this PDF:_**
[Mobility Accounts Market Sounding Summary Report_FINAL_Oct2021.pdf](https://github.com/cal-itp/website/files/7765602/Mobility.Accounts.Market.Sounding.Summary.Report_FINAL_Oct2021.pdf)

**Comment by esquared415** [comment]
I will be OOO 12/23 to 12/31, but I am happy to review these changes for approval on a staged site if the dev team is able to make them (know that dev team will be OOO as well).

**Comment by esquared415** [comment]
Hello, and Happy New Year! Do you have an eta for when the team might be able to make these requested edits, @thekaveman? Thanks!

**Comment by thekaveman** [comment]
Hi @esquared415, we're working on this. One question:

For the MST link under **Automating customer discounts**, do you want to link to the their top-level News page (current link), or to the news story announcing the launch of Benefits (https://mst.org/news_items/monterey-salinas-transit-mst-announces-discount-contactless-fares-for-riders-65-with-launch-of-benefits-eligibility-website/) - the link above in **Enabling contactless payments** points to the specific story.

**Comment by thekaveman** [comment]
Also @esquared415, it looks like the center blue block was sized for a single paragraph - the new content doesn't fit as well:

![image](https://user-images.githubusercontent.com/1783439/148138405-116b63cd-3e74-42c8-810d-51fd58d247f2.png)

We can definitely fit a single paragraph, or we'll have to see if @kristigrassi can update the background image SVG.

**Comment by thekaveman** [comment]
Preview site is available: https://deploy-preview-28--cal-itp-website.netlify.app/

**Comment by esquared415** [comment]
Hi @thekaveman! 

1. Please do point that link for Monterey-Salinas Transit to https://mst.org/news_items/monterey-salinas-transit-mst-announces-discount-contactless-fares-for-riders-65-with-launch-of-benefits-eligibility-website/
2. Benefits' background image SVG should be scaled to fit, so we will need to ask Kristi for support in scaling the file we have on Team Drive if it's not auto-scaling. 
3. Will re-look at the preview once the link is corrected (thanks!) and the Benefits background tile is scaled. 

Thank you!

**Comment by esquared415** [comment]
Hi again @thekaveman.

Just learned that Lilly and Gillian need the site updated with the Mobility Report **_tonight / early tomorrow._** 

So new tactic to fix Automating Customer Discounts while we wait for the blue tile background image SVG to be re-scaled.
Please make these two quick fixes to Automating Customer Discounts:
1. Point the link for Monterey-Salinas Transit to https://mst.org/news_items/monterey-salinas-transit-mst-announces-discount-contactless-fares-for-riders-65-with-launch-of-benefits-eligibility-website/
2. Run the 2 paragraphs of body text into 1 graph, for better fit within the existing SVG size.

Thanks much!!

**Comment by esquared415** [comment]
https://deploy-preview-28--cal-itp-website.netlify.app/ looks great @thekaveman. Please deploy.

Your call as to whether to leave this ticket open for SVG resize or to start a new ticket. 😄 

Thanks again!
