### ISSUE TITLE
"Getting to work" section \ paragraph 5: new ODS PDF to link 

### ISSUE THREAD

**Issue by esquared415** [cal-itp/website#44]
A URL linked within the ODS PR changed, and we need to update the PDF to reflect this new URL. 😬 

- [ ] Please upload this _revised_ ODS press release PDF (which contains the corrected URL):
[Cal-ITP.Open.Data.Standard.Improve.Transit.Agency.Operations.pdf](https://github.com/cal-itp/website/files/8847134/Cal-ITP.Open.Data.Standard.Improve.Transit.Agency.Operations.pdf)

- [ ] _Please make sure_ the asset link to this new PDF on website _remains_: 
https://www.calitp.org/assets/Cal-ITP.Open.Data.Standard.Improve.Transit.Agency.Operations.pdf

- [ ] Re-link the PDF from within this 1st sentence in the 5th paragraph of the "Getting to work" section:
In June 2022, Cal-ITP [announced a new open data standard] to improve transit agency operations and promote an interoperable transit ecosystem by improving the flow of data and information sharing. 

Thank you @thekaveman and team!

CC: @safrazier17

**Comment by thekaveman** [comment]
Updated with new PDF in [7836baf](https://github.com/cal-itp/website/commit/7836baf3c6a8b5a8a4446944ce0f54bebbb12822)

File name unchanged and link still works.

**Comment by esquared415** [comment]
Belated thanks, @thekaveman!
