### ISSUE TITLE
blue links hard to see on highlight background

### ISSUE THREAD

**Issue by kristigrassi** [cal-itp/website#9]
When I hover over a link it turns blue, and with the highlight background it's difficult to see. Can we keep it white?

<img width="575" alt="Screenshot 2021-01-05 at 12 20 49" src="https://user-images.githubusercontent.com/12957811/103677817-c837a500-4f50-11eb-9bfd-d2920ad5619b.png">

**Comment by krainboltgreene** [comment]
![Screen Shot 2021-01-14 at 7 51 09 PM](https://user-images.githubusercontent.com/334809/104679139-dc427b80-56a1-11eb-92f0-d826c17b71b8.png)


I can't reproduce, can you tell me what Browser/OS you're using?

**Comment by allejo** [comment]
Looks like the blue hover color was coming in from the Reboot stylesheet. I've changed it to keep a white color on hover and made the underline dotted (on hover and focus) so there's some visual indication that it has focus.

![image](https://user-images.githubusercontent.com/1246453/120757595-9a399b00-c4c5-11eb-8703-46b8724047c1.png)
